exports.iconCompMap = {
    'icon-shurukuang': 'TAK_INPUT',
    'icon-wenzi': 'TAK_TEXT'
};

exports.unitCompIcons = [{
    key: 'icon-xunhuan',
    name: '循环'
}, {
    key: 'icon-zuzhuangqiang',
    name: '组装枪'
}, {
    key: 'icon-yumingguanli',
    name: '域名管理'
}, {
    key: 'icon-qiehuan',
    name: '切换'
}, {
    key: 'icon-tubiao',
    name: '图标'
}, {
    key: 'icon-bingtu',
    name: '饼图'
}, {
    key: 'icon-shangji',
    name: '上级'
}, {
    key: 'icon-tuozhuai',
    name: '拖拽'
}, {
    key: 'icon-shu',
    name: '树'
}, {
    key: 'icon-quyutu',
    name: '区域图'
}, {
    key: 'icon-shipin',
    name: '视频'
}, {
    key: 'icon-juxing',
    name: '矩形'
}, {
    key: 'icon-baocun_mian',
    name: '保存 面性'
}, {
    key: 'icon-tubiaozhexiantu',
    name: '折线图'
}, {
    key: 'icon-shurukuang',
    name: '输入框'
}, {
    key: 'icon-xinjian',
    name: '新建'
}, {
    key: 'icon-zhibiao',
    name: '指标'
}, {
    key: 'icon-yuanliao',
    name: '原料'
}, {
    key: 'icon-yuming',
    name: '域名'
}, {
    key: 'icon-anniu',
    name: '按钮'
}, {
    key: 'icon-shangyibu',
    name: '上一步'
}, {
    key: 'icon-zujian',
    name: '组件'
}, {
    key: 'icon-wenzi',
    name: '文字'
}, {
    key: 'icon-tubiaozhuzhuangtu',
    name: '图表  柱状图'
}, {
    key: 'icon-caidan',
    name: '菜单'
}, {
    key: 'icon-zhedie',
    name: '折叠'
}, {
    key: 'icon-sanjiaoxing',
    name: '三角形'
}, {
    key: 'icon-huanzhuangtu',
    name: '环状图'
}, {
    key: 'icon-yinpin',
    name: '音频'
}, {
    key: 'icon-quanjituanxiangmuguanli',
    name: '全集团项目管理'
}, {
    key: 'icon-liebiao_huaban1',
    name: '列表'
}, {
    key: 'icon-tishi3',
    name: '提示 (3)'
}, {
    key: 'icon-switch',
    name: '切换'
}, {
    key: 'icon-yuanxing',
    name: '圆形'
}, {
    key: 'icon-pintu',
    name: '拼图'
}, {
    key: 'icon-yemian',
    name: '页面'
}, {
    key: 'icon-fuzhi',
    name: '复制'
}, {
    key: 'icon-lie',
    name: '折叠面板'
}, {
    key: 'icon-danchuang',
    name: '弹窗'
}, {
    key: 'icon-biaoge',
    name: '表格'
}, {
    key: 'icon-xian',
    name: '线'
}, {
    key: 'icon-rili',
    name: '日 历'
}, {
    key: 'icon-iconoption',
    name: '单选'
}, {
    key: 'icon-kuang',
    name: '框'
}, {
    key: 'icon-xuanze1',
    name: '多选择项1'
}, {
    key: 'icon-xiaji',
    name: '下级'
}, {
    key: 'icon-tupian',
    name: '图 片'
}, {
    key: 'icon-zuzhuangguanli',
    name: '组装管理'
}, {
    key: 'icon-moxingzuzhuang',
    name: '模型组装'
}, {
    key: 'icon-fenye',
    name: '分页'
}, {
    key: 'icon-duohangshuru',
    name: '手风琴'
}, {
    key: 'icon-shijian',
    name: '时 间'
}, {
    key: 'icon-liuchengtuh5-29',
    name: '下一步'
}];
